name: optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.4
  - pip=19.2.3
  - numpy=1.16.5
  - pandas=0.25.1
  - gurobi=8.1.1
  - pip:
    - pulp>=1.6.1,<=1.7.0
    - deap>=1.3,<=1.4
    - tabulate>=0.8.5,<=0.9.0
  
 
